"""Regenerate `quranic_phonemizer/data/render/ipa.yaml`, the output alphabet.

A row per feature tuple the model can actually produce, composed here once.

Run: python tools/build_render_map.py
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from quranic_phonemizer.model.canon import CanonLetter as L  # noqa: E402
from quranic_phonemizer.model.canon import Quality  # noqa: E402

#: Plain token per letter; four are inherently emphatic and carry the mark here.
BASE: dict[L, str] = {
    L.HAMZA: "ʔ", L.BA: "b", L.TA: "t", L.THA: "θ", L.JEEM: "ʒ",
    L.HA: "ħ", L.KHA: "x", L.DAL: "d", L.THAL: "ð", L.RA: "r",
    L.ZAY: "z", L.SEEN: "s", L.SHEEN: "ʃ", L.SAD: "sˤ", L.DAD: "dˤ",
    L.TAH: "tˤ", L.ZAH: "ðˤ", L.AIN: "ʕ", L.GHAIN: "ɣ", L.FA: "f",
    L.QAF: "q", L.KAF: "k", L.LAM: "l", L.MEEM: "m", L.NOON: "n",
    L.HEH: "h", L.WAW: "w", L.YA: "j", L.ALIF: "ʔ", L.TAA_MARBUTA: "t",
}

#: Emphatic token for the two letters whose plain and emphatic forms differ.
EMPHATIC = {L.RA: "rˤ", L.LAM: "lˤ"}

#: Nasalized consonants; unlike plain ones, gemination does not double the token.
NASALIZED = {L.NOON: "ñ", L.MEEM: "m̃", L.WAW: "w̃", L.YA: "j̃"}

#: Only these can be recoloured emphatic: the seven letters of istilaa, plus
#: raa and the divine lam. Generating the axis for the rest gave every wrong
#: tuple a plausible token and made `NotationError` unreachable.
HEAVY_CAPABLE = frozenset(
    {L.KHA, L.SAD, L.DAD, L.TAH, L.ZAH, L.GHAIN, L.QAF, L.RA, L.LAM}
)

#: Emphasis spreads onto a following `a` and onto no other vowel.
EMPHATIC_VOWEL = frozenset({Quality.A})

VOWEL = {Quality.A: "a", Quality.U: "u", Quality.I: "i", Quality.E: "e"}

#: Ghunnah has no emphatic form: no rule recolours a nasal.
NASAL_PLACES = {"bilabial": "m̃", "assimilated": "ŋ"}


def consonant_rows() -> list[str]:
    rows = []
    for letter in L:
        for geminate in (False, True):
            for emphatic in _axis(letter in HEAVY_CAPABLE):
                for nasal in _axis(letter in NASALIZED):
                    key = (
                        f"{letter.value}|{int(geminate)}|"
                        f"{int(emphatic)}|{int(nasal)}"
                    )
                    token = _consonant(letter, geminate, emphatic, nasal)
                    rows.append(f'  "{key}": "{token}"')
    return rows


def _axis(possible: bool) -> tuple[bool, ...]:
    return (False, True) if possible else (False,)


def _consonant(letter: L, geminate: bool, emphatic: bool, nasal: bool) -> str:
    if nasal:
        return NASALIZED[letter]
    base = EMPHATIC[letter] if (emphatic and letter in EMPHATIC) else BASE[letter]
    return base * 2 if geminate else base


def vowel_rows() -> list[str]:
    rows = []
    for quality in VOWEL:
        for long in (False, True):
            for emphatic in _axis(quality in EMPHATIC_VOWEL):
                token = (
                    VOWEL[quality] + ("ˤ" if emphatic else "") + (":" if long else "")
                )
                rows.append(
                    f'  "{quality.value}|{int(long)}|{int(emphatic)}": "{token}"'
                )
    return rows


def main() -> int:
    out = [
        "# The output alphabet: the only file in the package holding a phoneme",
        "# string. Generated by tools/build_render_map.py.",
        "#",
        "# One row per feature tuple the model can produce, and no others -- a",
        "# tuple with no row is a NotationError, which is the point.",
        "schema_version: 1",
        "notation: ipa",
        "",
        "consonants:",
        *consonant_rows(),
        "",
        "vowels:",
        *vowel_rows(),
        "",
        "nasals:",
        *[f'  "{place}|0": "{token}"' for place, token in NASAL_PLACES.items()],
        "",
        "releases:",
        '  "qalqala": "Q"',
        "",
    ]
    target = ROOT / "quranic_phonemizer" / "data" / "render" / "ipa.yaml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {target} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
