"""Generate `data/render/<notation>.yaml` — the only file with output symbols.

The render map is a **total lookup over the complete `Sound` feature tuple**,
with no composition performed at runtime (ADR-007 §3). Composition happens
here, once, so that a case like `(NOON, geminate, nasal) -> ñ` can simply be
written down: the frozen snapshot has 4,098 `ñ` and zero `nn`, so any runtime
rule that doubled a symbol would break parity.

Run:  python tools/build_render_map.py
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from quranic_phonemizer.model.canon import CanonLetter as L  # noqa: E402
from quranic_phonemizer.model.canon import Quality  # noqa: E402

#: The plain token of each letter. Four letters are inherently emphatic and
#: carry their mark here rather than acquiring it from a rule.
BASE: dict[L, str] = {
    L.HAMZA: "ʔ", L.BA: "b", L.TA: "t", L.THA: "θ", L.JEEM: "ʒ",
    L.HA: "ħ", L.KHA: "x", L.DAL: "d", L.THAL: "ð", L.RA: "r",
    L.ZAY: "z", L.SEEN: "s", L.SHEEN: "ʃ", L.SAD: "sˤ", L.DAD: "dˤ",
    L.TAH: "tˤ", L.ZAH: "ðˤ", L.AIN: "ʕ", L.GHAIN: "ɣ", L.FA: "f",
    L.QAF: "q", L.KAF: "k", L.LAM: "l", L.MEEM: "m", L.NOON: "n",
    L.HEH: "h", L.WAW: "w", L.YA: "j", L.ALIF: "ʔ", L.TAA_MARBUTA: "t",
}

#: Letters whose emphatic realization is a separate token rather than the
#: plain one. The four above are emphatic already; these two acquire it.
EMPHATIC = {L.RA: "rˤ", L.LAM: "lˤ"}

#: Nasalized consonants. Measured in the frozen continuous snapshot: `ñ`
#: 4,098, `m̃` 3,254, `w̃` 2,192, `j̃` 1,123 — and `w̃` and `ww` are distinct
#: tokens from the same letter with the same gemination, which is the whole
#: argument for keying on the complete tuple.
NASALIZED = {L.NOON: "ñ", L.MEEM: "m̃", L.WAW: "w̃", L.YA: "j̃"}

VOWEL = {Quality.A: "a", Quality.U: "u", Quality.I: "i",
         Quality.IMALA: "e", Quality.ISHMAM: "u"}


def consonant_rows() -> list[str]:
    rows = []
    for letter in L:
        for geminate in (False, True):
            for emphatic in (False, True):
                for nasal in (False, True):
                    token = _consonant(letter, geminate, emphatic, nasal)
                    key = (
                        f"{letter.value}|{int(geminate)}|"
                        f"{int(emphatic)}|{int(nasal)}"
                    )
                    rows.append(f'  "{key}": "{token}"')
    return rows


def _consonant(letter: L, geminate: bool, emphatic: bool, nasal: bool) -> str:
    if nasal:
        base = NASALIZED.get(letter, BASE[letter])
        return base if letter in NASALIZED else base * (2 if geminate else 1)
    base = EMPHATIC[letter] if (emphatic and letter in EMPHATIC) else BASE[letter]
    return base * 2 if geminate else base


def vowel_rows() -> list[str]:
    rows = []
    for quality in Quality:
        for long in (False, True):
            for emphatic in (False, True):
                token = VOWEL[quality] + ("ˤ" if emphatic else "") + (":" if long else "")
                key = f"{quality.value}|{int(long)}|{int(emphatic)}"
                rows.append(f'  "{key}": "{token}"')
    return rows


def main() -> int:
    out = [
        "# The output alphabet. The only file in the package that contains a",
        "# phoneme string, and no rule may read it (ADR-007 §3).",
        "#",
        "# Generated by tools/build_render_map.py. Keyed on the complete Sound",
        "# feature tuple so the lookup is total and performs no composition:",
        "# the snapshot has 4,098 `ñ` and zero `nn`, so a runtime rule that",
        "# doubled a symbol would break parity.",
        "schema_version: 1",
        "notation: ipa",
        "",
        "consonants:",
        *consonant_rows(),
        "",
        "vowels:",
        *vowel_rows(),
        "",
        "nasals:",
        '  "bilabial|0": "m̃"',
        '  "bilabial|1": "m̃"',
        '  "assimilated|0": "ŋ"',
        '  "assimilated|1": "ŋ"',
        "",
        "releases:",
        '  "qalqala": "Q"',
        "",
    ]
    target = ROOT / "quranic_phonemizer" / "data" / "render" / "ipa.yaml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {target} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
